### ISSUE TITLE
 What problem are you solving?

### ISSUE THREAD

**Issue by NikitaIT** [caiusno1/M-RS-SAUI-Prototype#15]
Hello, could you briefly explain the essence of the project.

I am currently working on building a constraint solver for complex domain spreadsheets and real-time updates.
The solver will suggest which cells need to be changed to meet the constraints.
I'm going to do this based on: Rete, PageRunk / GraphBolt, CRDT + op-log.

And I would like to ask what problem do you solve with this project? Perhaps you have already done any publications?

I am currently trying to quickly update `nools-ts`, but it is very poorly written, I am not sure if it is wise to continue. The build is not yet fully updated, but I'm almost done with that. Perhaps you know some better solutions in this direction?
https://github.com/NikitaIT/nools-ts

**Comment by NikitaIT** [comment]
I found this paper, but I don't see your name there. http://ceur-ws.org/Vol-2355/paper6.pdf

**Comment by caiusno1** [comment]
Hi, thanks for your interest in my bachelor thesis topic. Yes the paper you found is one of the papers suggesting that there is a gap to close in Consistency Checks and Consistency establishment for adaptive UIs. I used it as a motivation for my thesis. Currently there is no paper about my thesis but there is one in review for the HCSE 2020. I am not sure whether you face a similar problem than that that I tried to solve in my bachelor thesis. To be short: I present in my thesis an approach to synchronize context properties like User age, environment, light level ... to a User Interface as Context aware UI adaptations with the promise to take a closer look on conflicting UI modifications and appropriate solution  to the same by introducing a priority system. By using a formalism called Triple Graph Grammars I were able to argue about appropriate solutions to conflicting adaptations. You can think of an UI adaptation for example as the modification of screen light level considering the environmental light level (e.g. Night Mode). I wrote an own typing for Nools for using in TypeScript (was easier for me. Especially because nools is not that complex and will be most probably not updated very soon). If you have any additional questions please let me know :). Bests Kai

**Comment by caiusno1** [comment]
Maybe a sidenote Dr. Anthony Anjorin was the first examiner of my thesis and Dr. Enes Yigitbas was my thesis superviser.

**Comment by NikitaIT** [comment]
Oh, lucky. My thesis superviser - noname, who won't even read what I write) 
What libraries on js / ts can be used for algorithms and TGG? I only found this: https://github.com/ihh/graphgram

**Comment by caiusno1** [comment]
The library you found seems to be very interesting. I implemented a similar approach also doing graph rewriting. The difference is that the library u found implements graph grammers i think pair graph grammars while mine triggEngine implements Triple Graph Grammers. The second is more expressive (Prof. Andy Schürr can explain that even better. I read a summary of his phd thesis. He invented TGG). For implementing my synchronizer I used: nools and json diff patch library. I implemented a semantic similar to double pushout but not that concept directly. Nowerdays I would implement a categorical pushout directly because it will give u nice properties but at that time i didn t know about that therefore i simulated that behavior :-).

**Comment by caiusno1** [comment]
Jetzt gibt es n Paper:

Biermeier K., Yigitbas E., Weidmann N., Engels G. (2022) Ensuring User Interface Adaptation Consistency Through Triple Graph Grammars. In: Ardito C. et al. (eds) Sense, Feel, Design. INTERACT 2021. Lecture Notes in Computer Science, vol 13198. Springer, Cham. https://doi.org/10.1007/978-3-030-98388-8_17
